version: '3.7'

services:
  django_gunicorn:
    build: .
    volumes:
      - ./src:/algoproject/src
    ports:
      - "8000:8000"
      - '80:80'
      - '443:443'
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

